baseURL = "https://example.com/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Søren Flø Larsen"
theme = "hallo"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]

[Author]
    name = "Søren"

[params]

    [[params.links]]
        icon = "linkedin"
        title = "LinkedIn"
        url = "https://www.linkedin.com/in/søren-flø-larsen/"

    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "E-mail"
        url = "mailto:soren@sbfp.dk"
