baseURL = "https://sbfp.github.io/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Søren Flø Larsen"
theme = "hallo"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]

[Author]
    name = "Søren"

[params]

    [[params.links]]
        icon = "linkedin"
        title = "LinkedIn"
        url = "https://www.linkedin.com/in/søren-flø-larsen/"

    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "E-mail"
        url = "mailto:soren@sbfp.dk"

    [[params.links]]
        iconset = "fas"
        icon = "user-tie"
        title = "About me"
        url = "#about"

    [[params.links]]
        iconset = "fas"
        icon = "briefcase"
        title = "Employment history"
        url = "#career"

    [[params.links]]
        iconset = "fas"
        icon = "graduation-cap"
        title = "Education"
        url = "#education"


